USE [master]
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Teleregistret')
BEGIN
	/****** Object:  Database [Teleregistret]    Script Date: 2021-04-27 08:42:44 ******/
	CREATE DATABASE [Teleregistret]
	CONTAINMENT = NONE
	ON  PRIMARY 
	( NAME = N'Teleregistret', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Teleregistret.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	LOG ON 
	( NAME = N'LKTelereg_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LKTelereg_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	WITH CATALOG_COLLATION = DATABASE_DEFAULT

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teleregistret].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [Teleregistret] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [Teleregistret] SET ANSI_NULLS OFF 
ALTER DATABASE [Teleregistret] SET ANSI_PADDING OFF 
ALTER DATABASE [Teleregistret] SET ANSI_WARNINGS OFF 
ALTER DATABASE [Teleregistret] SET ARITHABORT OFF 
ALTER DATABASE [Teleregistret] SET AUTO_CLOSE ON 
ALTER DATABASE [Teleregistret] SET AUTO_SHRINK OFF 
ALTER DATABASE [Teleregistret] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [Teleregistret] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [Teleregistret] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [Teleregistret] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [Teleregistret] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [Teleregistret] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [Teleregistret] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [Teleregistret] SET  ENABLE_BROKER 
ALTER DATABASE [Teleregistret] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [Teleregistret] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [Teleregistret] SET TRUSTWORTHY OFF 
ALTER DATABASE [Teleregistret] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [Teleregistret] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [Teleregistret] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [Teleregistret] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [Teleregistret] SET RECOVERY SIMPLE 
ALTER DATABASE [Teleregistret] SET  MULTI_USER 
ALTER DATABASE [Teleregistret] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [Teleregistret] SET DB_CHAINING OFF 
ALTER DATABASE [Teleregistret] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE [Teleregistret] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [Teleregistret] SET DELAYED_DURABILITY = DISABLED 
ALTER DATABASE [Teleregistret] SET ACCELERATED_DATABASE_RECOVERY = OFF  
ALTER DATABASE [Teleregistret] SET QUERY_STORE = OFF
ALTER DATABASE [Teleregistret] SET  READ_WRITE 
END;
GO

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'test')
	/****** Object:  Login [test]    Script Date: 2021-04-27 08:44:49 ******/
	CREATE LOGIN [test] WITH PASSWORD=N'Password1!', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
	GO
GO

USE [Teleregistret]
GO

/****** Object:  User [test]    Script Date: 2021-04-27 08:47:02 ******/
DROP USER IF EXISTS [test]
GO

/****** Object:  User [test]    Script Date: 2021-04-27 08:47:02 ******/
CREATE USER [test] FOR LOGIN [test] WITH DEFAULT_SCHEMA=[dbo]
GO